int CUSTOMER_ID = 0;
int CUSTOMER_NAME = 1;
int CUSTOMER_SSN = 2;
int CUSTOMER_ADDRESS = 3;
int CUSTOMER_PHONE = 4;
int CUSTOMER_EMAIL = 5;

int ACCOUNT_ID = 0;
int ACCOUNT_CUSTOMERID = 1;
int ACCOUNT_ACCOUNT_NUMBER = 2;
int ACCOUNT_NAME = 3;
int ACCOUNT_BALANCE = 4;
int ACCOUNT_DATE = 5;

int TRANSACTION_ID = 0;
int TRANSACTION_FROMID = 1;
int TRANSACTION_TOID = 2;
int TRANSACTION_AMOUNT = 3;
int TRANSACTION_DATE = 4;
